name: linter

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: composer install
        uses: php-actions/composer@v6
        with:
          php_version: "8.4"
          version: 2
          command: install --prefer-dist --no-progress

      - name: Check Rector
        run: ./vendor/bin/rector --dry-run

      - name: Check Pint
        run: ./vendor/bin/pint --test

      - name: Check PHPStan
        run: ./vendor/bin/phpstan analyse
